[workspace]
members = [ "qbsp_macros" ]

[workspace.package]
version = "0.1.0"
edition = "2021"

[package]
name = "qbsp"
version.workspace = true
edition.workspace = true

[dependencies]
glam = "0.29"
image = { version = "0.25", default-features = false }
smallvec = "1"
strum = { version = "0.26", features = ["derive"] }
texture_packer = { version = "0.29", optional = true }
thiserror = "2.0"
qbsp_macros = { path = "qbsp_macros" }
derive_more = { version = "2", features = ["deref", "deref_mut", "into_iterator"] }

[features]
default = [ "meshing" ]
meshing = [ "dep:texture_packer" ]
