[workspace]
members = [ "q1bsp_macros" ]

[workspace.package]
version = "0.1.0"
edition = "2021"

[package]
name = "q1bsp"
version.workspace = true
edition.workspace = true

[dependencies]
glam = "0.29"
image = { version = "0.25", default-features = false }
smallvec = "1"
strum = { version = "0.26.3", features = ["derive"] }
texture_packer = { version = "0.29", optional = true }
thiserror = "2.0"
q1bsp_macros = { path = "q1bsp_macros" }

[features]
default = [ "meshing" ]
meshing = [ "dep:texture_packer" ]
